#!/bin/bash

# Function to clear the screen
clear_screen() {
    tput clear
}

# Function to generate a random number between a range
random_number() {
    local min=$1
    local max=$2
    echo $((RANDOM % (max - min + 1) + min))
}

# Function to generate random colors for fireworks
random_color() {
    local colors=("31" "32" "33" "34" "35" "36")
    local index=$(random_number 0 5)
    echo ${colors[$index]}
}

# Function to simulate fireworks
fireworks() {
    local columns=$(tput cols)
    local lines=$(tput lines)
    local num_fireworks=10

    for ((i = 0; i < num_fireworks; i++)); do
        local x=$(random_number 0 $columns)
        local y=$(random_number 0 $lines)
        local color=$(random_color)

        tput cup $y $x
        echo -e "\e[1;${color}m*\e[0m"
    done

    sleep 1
}

# Function to simulate lightning
lightning() {
    clear_screen
    echo -e "\e[1;33m"
    cat << "EOF"
    \    /\
     )  ( ')
    (  /  )
     \(__)|
EOF
    echo -e "\e[0m"
    sleep 1
}

# Function to simulate rain
rain() {
    local columns=$(tput cols)
    local lines=$(tput lines)
    local num_drops=100

    for ((i = 0; i < num_drops; i++)); do
        local x=$(random_number 0 $columns)
        local y=$(random_number 0 $lines)

        tput cup $y $x
        echo -e "\e[34m|\e[0m"
    done

    sleep 1
}

# Main script
clear_screen
while true; do
    fireworks
    lightning
    rain
done

